/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 20:22:43 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Automatizacao_ESTest extends Automatizacao_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        Automatizacao.parseFile("k{z:#u)\"~[", (Estado) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Automatizacao", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Estado estado0 = new Estado();
      Automatizacao.parseFile("", estado0);
      assertEquals("01/01/2018", estado0.getData());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Automatizacao automatizacao0 = new Automatizacao();
  }
}
