/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 20:33:06 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class formula2_ESTest extends formula2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      formula2 formula2_0 = new formula2();
      SmartSpeaker smartSpeaker0 = new SmartSpeaker("$Ewv?.7n", false, 0, "$Ewv?.7n", "$Ewv?.7n");
      double double0 = formula2_0.formula(smartSpeaker0);
      assertEquals(57.542399999999994, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      formula2 formula2_0 = new formula2();
      SmartSpeaker smartSpeaker0 = new SmartSpeaker();
      smartSpeaker0.setVolume((-238));
      double double0 = formula2_0.formula(smartSpeaker0);
      assertEquals((-1358.0006399999997), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      formula2 formula2_0 = new formula2();
      // Undeclared exception!
      try { 
        formula2_0.formula((SmartDevice) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("formula2", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      formula2 formula2_0 = new formula2();
      SmartBulb smartBulb0 = new SmartBulb("", true, (-4563), (-4563));
      double double0 = formula2_0.formula(smartBulb0);
      assertEquals(0.0, double0, 0.01);
  }
}
