/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 20:33:14 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class formula3_ESTest extends formula3_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      formula3 formula3_0 = new formula3();
      SmartSpeaker smartSpeaker0 = new SmartSpeaker();
      smartSpeaker0.setMarca("\n");
      double double0 = formula3_0.formula(smartSpeaker0);
      assertEquals(15.344639999999998, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      formula3 formula3_0 = new formula3();
      SmartSpeaker smartSpeaker0 = new SmartSpeaker();
      smartSpeaker0.setVolume((-1642));
      double double0 = formula3_0.formula(smartSpeaker0);
      assertEquals((-8388.4032), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      formula3 formula3_0 = new formula3();
      // Undeclared exception!
      try { 
        formula3_0.formula((SmartDevice) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("formula3", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      formula3 formula3_0 = new formula3();
      SmartBulb smartBulb0 = new SmartBulb();
      double double0 = formula3_0.formula(smartBulb0);
      assertEquals(0.0, double0, 0.01);
  }
}
