/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 20:00:39 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ControllerCasa_ESTest extends ControllerCasa_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      LinkedList<Casa> linkedList0 = new LinkedList<Casa>();
      linkedList0.add((Casa) null);
      linkedList0.add((Casa) null);
      Casa casa0 = ControllerCasa.indiceCasa(linkedList0);
      assertNull(casa0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      LinkedList<Casa> linkedList0 = new LinkedList<Casa>();
      Casa casa0 = new Casa();
      linkedList0.add(casa0);
      Casa casa1 = ControllerCasa.indiceCasa(linkedList0);
      assertTrue(linkedList0.contains(casa1));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      LinkedList<Casa> linkedList0 = new LinkedList<Casa>();
      Casa casa0 = new Casa();
      casa0.setCustoInstalacao(30.0);
      linkedList0.add(casa0);
      Casa casa1 = ControllerCasa.indiceCasa(linkedList0);
      assertTrue(linkedList0.contains(casa1));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      // Undeclared exception!
      try { 
        ControllerCasa.run((Estado) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ControllerCasa", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      SystemInUtil.addInputLine("");
      LinkedList<Casa> linkedList0 = new LinkedList<Casa>();
      // Undeclared exception!
      try { 
        ControllerCasa.indiceCasa(linkedList0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      // Undeclared exception!
      try { 
        ControllerCasa.indiceCasa((List<Casa>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ControllerCasa", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      // Undeclared exception!
      try { 
        ControllerCasa.EscolhaDispositivos("ETPJyhi fNft1,t-", false);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      // Undeclared exception!
      try { 
        ControllerCasa.EscolhaDispositivos("]0G", false);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      SmartDevice smartDevice0 = ControllerCasa.EscolhaDispositivos("0", true);
      assertNull(smartDevice0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SystemInUtil.addInputLine("A-]%!G");
      // Undeclared exception!
      try { 
        ControllerCasa.EscolhaDispositivos("A-]%!G", false);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SystemInUtil.addInputLine("21");
      // Undeclared exception!
      try { 
        ControllerCasa.EscolhaDispositivos("-]%!G", true);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      // Undeclared exception!
      try { 
        ControllerCasa.EscolhaDispositivos("1", true);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      LinkedList<Casa> linkedList0 = new LinkedList<Casa>();
      // Undeclared exception!
      try { 
        ControllerCasa.indiceCasa(linkedList0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SystemInUtil.addInputLine("-]%!G");
      Estado estado0 = new Estado();
      List<Casa> list0 = estado0.getCasas();
      // Undeclared exception!
      try { 
        ControllerCasa.indiceCasa(list0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SystemInUtil.addInputLine("8");
      Estado estado0 = new Estado();
      // Undeclared exception!
      try { 
        ControllerCasa.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SystemInUtil.addInputLine("7");
      Estado estado0 = new Estado();
      ControllerCasa.run(estado0);
      assertEquals("01/01/2018", estado0.getData());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SystemInUtil.addInputLine("6");
      Estado estado0 = new Estado();
      HashMap<String, SmartDevice> hashMap0 = new HashMap<String, SmartDevice>();
      HashMap<String, HashSet<String>> hashMap1 = new HashMap<String, HashSet<String>>();
      Casa casa0 = new Casa(hashMap0, hashMap1, "6", "6", (Fornecedores) null);
      estado0.addCasa(casa0);
      // Undeclared exception!
      try { 
        ControllerCasa.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SystemInUtil.addInputLine("6");
      Estado estado0 = new Estado();
      ControllerCasa.run(estado0);
      assertEquals("01/01/2018", estado0.getData());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SystemInUtil.addInputLine("5");
      Estado estado0 = new Estado();
      Casa casa0 = new Casa();
      estado0.addCasa(casa0);
      // Undeclared exception!
      try { 
        ControllerCasa.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SystemInUtil.addInputLine("5");
      Estado estado0 = new Estado();
      ControllerCasa.run(estado0);
      assertEquals("01/01/2018", estado0.getData());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SystemInUtil.addInputLine("4");
      Estado estado0 = new Estado();
      FornecEndesa fornecEndesa0 = new FornecEndesa(0.0);
      estado0.addForn(fornecEndesa0);
      // Undeclared exception!
      try { 
        ControllerCasa.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SystemInUtil.addInputLine("4");
      Estado estado0 = new Estado();
      // Undeclared exception!
      try { 
        ControllerCasa.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      LinkedList<Casa> linkedList0 = new LinkedList<Casa>();
      Casa casa0 = new Casa();
      linkedList0.add(casa0);
      LinkedList<Fornecedores> linkedList1 = new LinkedList<Fornecedores>();
      Estado estado0 = new Estado(linkedList0, linkedList1);
      // Undeclared exception!
      try { 
        ControllerCasa.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      Estado estado0 = new Estado();
      ControllerCasa.run(estado0);
      assertEquals("01/01/2018", estado0.getData());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      Estado estado0 = new Estado();
      Casa casa0 = new Casa();
      estado0.addCasa(casa0);
      // Undeclared exception!
      try { 
        ControllerCasa.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      Estado estado0 = new Estado();
      ControllerCasa.run(estado0);
      assertEquals("01/01/2018", estado0.getData());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      Estado estado0 = new Estado();
      // Undeclared exception!
      try { 
        ControllerCasa.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      SystemInUtil.addInputLine("21");
      Estado estado0 = new Estado();
      // Undeclared exception!
      try { 
        ControllerCasa.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      Estado estado0 = new Estado();
      ControllerCasa.run(estado0);
      assertEquals("01/01/2018", estado0.getData());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ControllerCasa controllerCasa0 = new ControllerCasa();
  }
}
