/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 20:32:49 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ControllerAutomatizacao_ESTest extends ControllerAutomatizacao_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        ControllerAutomatizacao.run((Estado) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Automatizacao", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ControllerAutomatizacao controllerAutomatizacao0 = new ControllerAutomatizacao();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Estado estado0 = new Estado();
      // Undeclared exception!
      try { 
        ControllerAutomatizacao.run(estado0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 179, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }
}
