/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 20:15:40 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ControllerEstatistica_ESTest extends ControllerEstatistica_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      Estado estado0 = new Estado();
      FornecEDP fornecEDP0 = new FornecEDP();
      estado0.addForn(fornecEDP0);
      // Undeclared exception!
      try { 
        ControllerEstatistica.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      Estado estado0 = new Estado();
      HashMap<String, SmartDevice> hashMap0 = new HashMap<String, SmartDevice>();
      Casa casa0 = new Casa();
      Map<String, HashSet<String>> map0 = casa0.getDivisoes();
      FornecJomar fornecJomar0 = new FornecJomar();
      Casa casa1 = new Casa(hashMap0, map0, "1", "", fornecJomar0);
      estado0.addCasa(casa1);
      // Undeclared exception!
      try { 
        ControllerEstatistica.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      Estado estado0 = new Estado();
      Casa casa0 = new Casa();
      estado0.addCasa(casa0);
      // Undeclared exception!
      try { 
        ControllerEstatistica.run(estado0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Casa", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SystemInUtil.addInputLine("5");
      Estado estado0 = new Estado();
      // Undeclared exception!
      try { 
        ControllerEstatistica.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SystemInUtil.addInputLine("4");
      Estado estado0 = new Estado();
      // Undeclared exception!
      try { 
        ControllerEstatistica.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SystemInUtil.addInputLine("3");
      Estado estado0 = new Estado();
      // Undeclared exception!
      try { 
        ControllerEstatistica.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SystemInUtil.addInputLine("2");
      Estado estado0 = new Estado();
      // Undeclared exception!
      try { 
        ControllerEstatistica.run(estado0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SystemInUtil.addInputLine("1");
      Estado estado0 = new Estado();
      // Undeclared exception!
      try { 
        ControllerEstatistica.run(estado0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SystemInUtil.addInputLine("80");
      Estado estado0 = new Estado();
      // Undeclared exception!
      try { 
        ControllerEstatistica.run(estado0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SystemInUtil.addInputLine("0");
      Estado estado0 = new Estado();
      ControllerEstatistica.run(estado0);
      assertEquals("01/01/2018", estado0.getData());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ControllerEstatistica controllerEstatistica0 = new ControllerEstatistica();
  }
}
