/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 20:35:44 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FornecEDP_ESTest extends FornecEDP_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FornecEDP fornecEDP0 = new FornecEDP(0.6);
      Fornecedores fornecedores0 = fornecEDP0.clone();
      assertEquals("", fornecedores0.getFormula());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FornecEDP fornecEDP0 = null;
      try {
        fornecEDP0 = new FornecEDP((FornecEDP) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Fornecedores", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FornecEDP fornecEDP0 = new FornecEDP();
      FornecEDP fornecEDP1 = new FornecEDP(fornecEDP0);
      assertEquals("", fornecEDP1.getFormula());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FornecEDP fornecEDP0 = new FornecEDP((-1.0));
      Fornecedores fornecedores0 = fornecEDP0.clone();
      assertEquals("", fornecedores0.getFormula());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FornecEDP fornecEDP0 = new FornecEDP("Fornecedores");
      Fornecedores fornecedores0 = fornecEDP0.clone();
      assertEquals(0.6, fornecedores0.getImposto(), 0.01);
  }
}
