/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 20:32:58 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class formula1_ESTest extends formula1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      formula1 formula1_0 = new formula1();
      SmartBulb smartBulb0 = new SmartBulb();
      double double0 = formula1_0.formula(smartBulb0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      formula1 formula1_0 = new formula1();
      SmartSpeaker smartSpeaker0 = new SmartSpeaker("", true, 0, "", "]E- eD$aBT*tnhC0");
      smartSpeaker0.setVolume((-3894));
      double double0 = formula1_0.formula(smartSpeaker0);
      assertEquals((-2061672.3072000002), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      formula1 formula1_0 = new formula1();
      // Undeclared exception!
      try { 
        formula1_0.formula((SmartDevice) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("formula1", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      formula1 formula1_0 = new formula1();
      SmartBulb smartBulb0 = new SmartBulb("", true, 2709, 2709);
      double double0 = formula1_0.formula(smartBulb0);
      assertEquals(2882405.1168000004, double0, 0.01);
  }
}
